# Form implementation generated from reading ui file 'delete.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiDeleteDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(434, 289)
        Dialog.setStyleSheet(
            "background-color:qlineargradient(spread:pad, x1:0.134423, y1:0.187, x2:0.935323, y2:0.909, stop:0 rgba(74, 0, 255, 255), stop:1 rgba(229, 30, 204, 255))")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(50, 20, 321, 251))
        self.frame.setStyleSheet("background-color: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_del = QtWidgets.QLabel(parent=self.frame)
        self.lbl_del.setMaximumSize(QtCore.QSize(300, 50))
        self.lbl_del.setStyleSheet("color:white;\n"
                                   "background-color: none;\n"
                                   "font: 12pt \"Berlin Sans FB\" bold;")
        self.lbl_del.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_del.setObjectName("lbl_del")
        self.verticalLayout.addWidget(self.lbl_del)
        self.lineEdit_id = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_id.setMaximumSize(QtCore.QSize(300, 30))
        self.lineEdit_id.setStyleSheet("font-size:12pt \"Berlin Sans FB\";\n"
                                       "padding-left: 10px;\n"
                                       "background-color: rgba(255,255,255,30);\n"
                                       "border:1px solid rgba(255,255,255,40);\n"
                                       "border-radius: 7px;")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.verticalLayout.addWidget(self.lineEdit_id)
        self.btn_del = QtWidgets.QPushButton(parent=self.frame)
        self.btn_del.setMaximumSize(QtCore.QSize(300, 60))
        self.btn_del.setStyleSheet("QPushButton{\n"
                                   "color:white;\n"
                                   "background-color: rgba(255,255,255,30);\n"
                                   "border:1px solid rgba(255,255,255,40);\n"
                                   "border-radius: 7px;\n"
                                   "width:400px;\n"
                                   "height:90px;\n"
                                   "font: 14pt \"Berlin Sans FB\";\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:hover{\n"
                                   "background-color:rgba(255,255,255,40);\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed{\n"
                                   "background-color:rgba(255,255,255,70);\n"
                                   "}")
        self.btn_del.setObjectName("btn_del")
        self.verticalLayout.addWidget(self.btn_del)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_del.setText(_translate("Dialog", "Введите id пользователя"))
        self.lineEdit_id.setPlaceholderText(_translate("Dialog", "Id"))
        self.btn_del.setText(_translate("Dialog", "Удалить"))
