# Form implementation generated from reading ui file 'insert.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiInsertDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(573, 689)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(573, 689))
        Dialog.setMaximumSize(QtCore.QSize(573, 689))
        Dialog.setMouseTracking(False)
        Dialog.setStyleSheet(
            "background-color:qlineargradient(spread:pad, x1:0.134423, y1:0.187, x2:0.935323, y2:0.909, stop:0 rgba(74, 0, 255, 255), stop:1 rgba(229, 30, 204, 255))")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(70, 50, 448, 571))
        self.frame.setStyleSheet("background-color: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setEnabled(True)
        self.label.setMaximumSize(QtCore.QSize(440, 50))
        self.label.setStyleSheet("color:white;\n"
                                 "background-color: none;\n"
                                 "font: 18pt \"Berlin Sans FB\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.name = QtWidgets.QLineEdit(parent=self.frame)
        self.name.setMinimumSize(QtCore.QSize(400, 40))
        self.name.setMaximumSize(QtCore.QSize(400, 40))
        self.name.setStyleSheet("font-size:12pt \"Berlin Sans FB\";\n"
                                "padding-left: 10px;\n"
                                "background-color: rgba(255,255,255,30);\n"
                                "border:1px solid rgba(255,255,255,40);\n"
                                "border-radius: 7px;")
        self.name.setText("")
        self.name.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.surname = QtWidgets.QLineEdit(parent=self.frame)
        self.surname.setMinimumSize(QtCore.QSize(400, 40))
        self.surname.setMaximumSize(QtCore.QSize(400, 40))
        self.surname.setStyleSheet("font-size:12pt;\n"
                                   "padding-left: 10px;\n"
                                   "background-color: rgba(255,255,255,30);\n"
                                   "border:1px solid rgba(255,255,255,40);\n"
                                   "border-radius: 7px;")
        self.surname.setObjectName("surname")
        self.verticalLayout.addWidget(self.surname)
        self.country = QtWidgets.QLineEdit(parent=self.frame)
        self.country.setMinimumSize(QtCore.QSize(400, 40))
        self.country.setMaximumSize(QtCore.QSize(400, 40))
        self.country.setStyleSheet("font-size:12pt;\n"
                                   "padding-left: 10px;\n"
                                   "background-color: rgba(255,255,255,30);\n"
                                   "border:1px solid rgba(255,255,255,40);\n"
                                   "border-radius: 7px;\n"
                                   "width:400;\n"
                                   "heigth:40;")
        self.country.setObjectName("country")
        self.verticalLayout.addWidget(self.country)
        self.city = QtWidgets.QLineEdit(parent=self.frame)
        self.city.setMinimumSize(QtCore.QSize(400, 40))
        self.city.setMaximumSize(QtCore.QSize(400, 40))
        self.city.setStyleSheet("font-size:12pt;\n"
                                "padding-left: 10px;\n"
                                "background-color: rgba(255,255,255,30);\n"
                                "border:1px solid rgba(255,255,255,40);\n"
                                "border-radius: 7px;")
        self.city.setObjectName("city")
        self.verticalLayout.addWidget(self.city)
        self.address = QtWidgets.QLineEdit(parent=self.frame)
        self.address.setMinimumSize(QtCore.QSize(400, 40))
        self.address.setMaximumSize(QtCore.QSize(400, 40))
        self.address.setStyleSheet("font-size:12pt;\n"
                                   "padding-left: 10px;\n"
                                   "background-color: rgba(255,255,255,30);\n"
                                   "border:1px solid rgba(255,255,255,40);\n"
                                   "border-radius: 7px;")
        self.address.setObjectName("address")
        self.verticalLayout.addWidget(self.address)
        self.date_of_birth = QtWidgets.QLineEdit(parent=self.frame)
        self.date_of_birth.setMinimumSize(QtCore.QSize(400, 40))
        self.date_of_birth.setMaximumSize(QtCore.QSize(400, 40))
        self.date_of_birth.setStyleSheet("font-size:12pt;\n"
                                         "padding-left: 10px;\n"
                                         "background-color: rgba(255,255,255,30);\n"
                                         "border:1px solid rgba(255,255,255,40);\n"
                                         "border-radius: 7px;")
        self.date_of_birth.setObjectName("date_of_birth")
        self.verticalLayout.addWidget(self.date_of_birth)
        self.phone = QtWidgets.QLineEdit(parent=self.frame)
        self.phone.setMinimumSize(QtCore.QSize(400, 40))
        self.phone.setMaximumSize(QtCore.QSize(400, 40))
        self.phone.setStyleSheet("font-size:12pt;\n"
                                 "padding-left: 10px;\n"
                                 "background-color: rgba(255,255,255,30);\n"
                                 "border:1px solid rgba(255,255,255,40);\n"
                                 "border-radius: 7px;")
        self.phone.setObjectName("phone")
        self.verticalLayout.addWidget(self.phone)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setMaximumSize(QtCore.QSize(400, 80))
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "color:white;\n"
                                      "background-color: rgba(255,255,255,30);\n"
                                      "border:1px solid rgba(255,255,255,40);\n"
                                      "border-radius: 7px;\n"
                                      "width:400px;\n"
                                      "height:90px;\n"
                                      "font: 14pt \"Berlin Sans FB\";\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgba(255,255,255,40);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed{\n"
                                      "background-color:rgba(255,255,255,70);\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "insert"))
        self.label.setText(_translate("Dialog", "Введите данные пользователя"))
        self.name.setPlaceholderText(_translate("Dialog", "Имя"))
        self.surname.setPlaceholderText(_translate("Dialog", "Фамилия"))
        self.country.setPlaceholderText(_translate("Dialog", "Страна"))
        self.city.setPlaceholderText(_translate("Dialog", "Город"))
        self.address.setPlaceholderText(_translate("Dialog", "Адрес"))
        self.date_of_birth.setPlaceholderText(_translate("Dialog", "Дата рождения в формате: YYYY-MM-DD"))
        self.phone.setPlaceholderText(_translate("Dialog", "Телефон в формате: +7(999)999-99-99"))
        self.pushButton.setText(_translate("Dialog", "Добавить данные"))

