# Form implementation generated from reading ui file 'save_filter.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiSaveFilterDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(695, 500)
        Dialog.setAccessibleDescription("")
        Dialog.setStyleSheet(
            "background-color:qlineargradient(spread:pad, x1:0.134423, y1:0.187, x2:0.935323, y2:0.909, stop:0 rgba(74, 0, 255, 255), stop:1 rgba(229, 30, 204, 255))")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(60, 30, 591, 451))
        self.frame.setStyleSheet("background-color: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setMaximumSize(QtCore.QSize(600, 60))
        self.label.setStyleSheet("color:white;\n"
                                 "background-color: none;\n"
                                 "font: 14pt \"Berlin Sans FB\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.comboBox.setStyleSheet("QComboBox{\n"
                                    "color:white;\n"
                                    "font-size:16pt;\n"
                                    "background-color: rgba(255,255,255,30);\n"
                                    "border:1px solid rgba(255,255,255,40);\n"
                                    "border-radius: 7px;\n"
                                    "}\n"
                                    "QComboBox:item{\n"
                                    "color:black;\n"
                                    "}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.lineEdit.setStyleSheet("font-size:12pt \"Berlin Sans FB\";\n"
                                    "padding-left: 10px;\n"
                                    "background-color: rgba(255,255,255,30);\n"
                                    "border:1px solid rgba(255,255,255,40);\n"
                                    "border-radius: 7px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "color:white;\n"
                                      "background-color: rgba(255,255,255,30);\n"
                                      "border:1px solid rgba(255,255,255,40);\n"
                                      "border-radius: 7px;\n"
                                      "width:400px;\n"
                                      "height:90px;\n"
                                      "font: 14pt \"Berlin Sans FB\";\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgba(255,255,255,40);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed{\n"
                                      "background-color:rgba(255,255,255,70);\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Выберите в каком формате сохранить результаты фильтра"))
        self.comboBox.setItemText(0, _translate("Dialog", "txt"))
        self.comboBox.setItemText(1, _translate("Dialog", "json"))
        self.lineEdit.setPlaceholderText(
            _translate("Dialog", "Название файла куда сохранить результат фильтра(без разрешения)"))
        self.pushButton.setText(_translate("Dialog", "Сохранить"))

