# Form implementation generated from reading ui file 'update.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiUpdateDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 690)
        Dialog.setMinimumSize(QtCore.QSize(550, 690))
        Dialog.setMaximumSize(QtCore.QSize(700, 690))
        Dialog.setStyleSheet(
            "background-color:qlineargradient(spread:pad, x1:0.134423, y1:0.187, x2:0.935323, y2:0.909, stop:0 rgba(74, 0, 255, 255), stop:1 rgba(229, 30, 204, 255))")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(70, 40, 421, 600))
        self.frame.setStyleSheet("background-color: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(400, 40))
        self.lineEdit.setMaximumSize(QtCore.QSize(400, 40))
        self.lineEdit.setStyleSheet("font-size:12pt \"Berlin Sans FB\";\n"
                                    "padding-left: 10px;\n"
                                    "background-color: rgba(255,255,255,30);\n"
                                    "border:1px solid rgba(255,255,255,40);\n"
                                    "border-radius: 7px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.btn_id = QtWidgets.QPushButton(parent=self.frame)
        self.btn_id.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_id.setStyleSheet("QPushButton{\n"
                                        "color:white;\n"
                                        "background-color: rgba(255,255,255,30);\n"
                                        "border:1px solid rgba(255,255,255,40);\n"
                                        "border-radius: 7px;\n"
                                        "width:400px;\n"
                                        "height:90px;\n"
                                        "font: 12pt \"Berlin Sans FB\";\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "background-color:rgba(255,255,255,40);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed{\n"
                                        "background-color:rgba(255,255,255,70);\n"
                                        "}")
        self.btn_id.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.btn_id)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setEnabled(True)
        self.label.setMaximumSize(QtCore.QSize(440, 50))
        self.label.setStyleSheet("color:white;\n"
                                 "background-color: none;\n"
                                 "font: 18pt \"Berlin Sans FB\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLineEdit(parent=self.frame)
        self.name.setMinimumSize(QtCore.QSize(400, 40))
        self.name.setMaximumSize(QtCore.QSize(400, 40))
        self.name.setStyleSheet("font-size:12pt \"Berlin Sans FB\";\n"
                                "padding-left: 10px;\n"
                                "background-color: rgba(255,255,255,30);\n"
                                "border:1px solid rgba(255,255,255,40);\n"
                                "border-radius: 7px;")
        self.name.setText("")
        self.name.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.name.setPlaceholderText("")
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.surname = QtWidgets.QLineEdit(parent=self.frame)
        self.surname.setMinimumSize(QtCore.QSize(400, 40))
        self.surname.setMaximumSize(QtCore.QSize(400, 40))
        self.surname.setStyleSheet("font-size:12pt;\n"
                                   "padding-left: 10px;\n"
                                   "background-color: rgba(255,255,255,30);\n"
                                   "border:1px solid rgba(255,255,255,40);\n"
                                   "border-radius: 7px;")
        self.surname.setPlaceholderText("")
        self.surname.setObjectName("surname")
        self.horizontalLayout_2.addWidget(self.surname)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.country = QtWidgets.QLineEdit(parent=self.frame)
        self.country.setMinimumSize(QtCore.QSize(400, 40))
        self.country.setMaximumSize(QtCore.QSize(400, 40))
        self.country.setStyleSheet("font-size:12pt;\n"
                                   "padding-left: 10px;\n"
                                   "background-color: rgba(255,255,255,30);\n"
                                   "border:1px solid rgba(255,255,255,40);\n"
                                   "border-radius: 7px;\n"
                                   "width:400;\n"
                                   "heigth:40;")
        self.country.setPlaceholderText("")
        self.country.setObjectName("country")
        self.horizontalLayout_3.addWidget(self.country)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.city = QtWidgets.QLineEdit(parent=self.frame)
        self.city.setMinimumSize(QtCore.QSize(400, 40))
        self.city.setMaximumSize(QtCore.QSize(400, 40))
        self.city.setStyleSheet("font-size:12pt;\n"
                                "padding-left: 10px;\n"
                                "background-color: rgba(255,255,255,30);\n"
                                "border:1px solid rgba(255,255,255,40);\n"
                                "border-radius: 7px;")
        self.city.setPlaceholderText("")
        self.city.setObjectName("city")
        self.horizontalLayout_4.addWidget(self.city)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.address = QtWidgets.QLineEdit(parent=self.frame)
        self.address.setMinimumSize(QtCore.QSize(400, 40))
        self.address.setMaximumSize(QtCore.QSize(400, 40))
        self.address.setStyleSheet("font-size:12pt;\n"
                                   "padding-left: 10px;\n"
                                   "background-color: rgba(255,255,255,30);\n"
                                   "border:1px solid rgba(255,255,255,40);\n"
                                   "border-radius: 7px;")
        self.address.setPlaceholderText("")
        self.address.setObjectName("address")
        self.horizontalLayout_5.addWidget(self.address)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.date_of_birth = QtWidgets.QLineEdit(parent=self.frame)
        self.date_of_birth.setMinimumSize(QtCore.QSize(400, 40))
        self.date_of_birth.setMaximumSize(QtCore.QSize(400, 40))
        self.date_of_birth.setStyleSheet("font-size:12pt;\n"
                                         "padding-left: 10px;\n"
                                         "background-color: rgba(255,255,255,30);\n"
                                         "border:1px solid rgba(255,255,255,40);\n"
                                         "border-radius: 7px;")
        self.date_of_birth.setPlaceholderText("")
        self.date_of_birth.setObjectName("date_of_birth")
        self.horizontalLayout_6.addWidget(self.date_of_birth)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.phone = QtWidgets.QLineEdit(parent=self.frame)
        self.phone.setMinimumSize(QtCore.QSize(400, 40))
        self.phone.setMaximumSize(QtCore.QSize(400, 40))
        self.phone.setStyleSheet("font-size:12pt;\n"
                                 "padding-left: 10px;\n"
                                 "background-color: rgba(255,255,255,30);\n"
                                 "border:1px solid rgba(255,255,255,40);\n"
                                 "border-radius: 7px;")
        self.phone.setPlaceholderText("")
        self.phone.setObjectName("phone")
        self.horizontalLayout_7.addWidget(self.phone)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.btn_update = QtWidgets.QPushButton(parent=self.frame)
        self.btn_update.setMaximumSize(QtCore.QSize(400, 70))
        self.btn_update.setStyleSheet("QPushButton{\n"
                                      "color:white;\n"
                                      "background-color: rgba(255,255,255,30);\n"
                                      "border:1px solid rgba(255,255,255,40);\n"
                                      "border-radius: 7px;\n"
                                      "width:400px;\n"
                                      "height:90px;\n"
                                      "font: 14pt \"Berlin Sans FB\";\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgba(255,255,255,40);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed{\n"
                                      "background-color:rgba(255,255,255,70);\n"
                                      "}")
        self.btn_update.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.btn_update)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Введите Id"))
        self.btn_id.setText(_translate("Dialog", "Подтвердить Id"))
        self.label.setText(_translate("Dialog", "Измените нужные поля"))
        self.btn_update.setText(_translate("Dialog", "Обновить"))
        self.name.setPlaceholderText(_translate("Dialog", "Имя"))
        self.surname.setPlaceholderText(_translate("Dialog", "Фамилия"))
        self.country.setPlaceholderText(_translate("Dialog", "Страна"))
        self.city.setPlaceholderText(_translate("Dialog", "Город"))
        self.address.setPlaceholderText(_translate("Dialog", "Адрес"))
        self.date_of_birth.setPlaceholderText(_translate("Dialog", "Дата рождения в формате: YYYY-MM-DD"))
        self.phone.setPlaceholderText(_translate("Dialog", "Телефон в формате: +7(999)999-99-99"))

